### ISSUE TITLE
SPIKE: Investigate Sharding & Shard Region data from Akka Management

### ISSUE THREAD

**Issue by CharlesAHunt** [Headstorm/shukra#12]
Determine if we can get shard region and sharding data in general from Akka Management API.

- Does Akka HTTP expose Cluster Sharding data?
- If so what is all the possible data we can collect and/or manage related to cluster sharding?
- How can we visualize and manage that data in the UI?

**Comment by kpasagada** [comment]
Akka management by default exposes shard details that belong to a shard region using its name. 
[Cluster HTTP Management](https://doc.akka.io/docs/akka-management/current/cluster-http-management.html)

However, Akka Management does not expose any details about shard regions (their names) itself.

In order to expose cluster shard region data and other actor data, "Developing Extensions" section of [Akka Management](https://doc.akka.io/docs/akka-management/current/akka-management.html) can be used.

**Comment by kpasagada** [comment]
https://petabridge.com/blog/cluster-sharding-technical-overview-akkadotnet contains details about retrieving cluster shard metadata by sending messages to the Shard Region actor.

**Comment by kpasagada** [comment]
The following piece of code can be used to retrieve all the shard type names (or regions) that are active in the cluster.
`akka.cluster.sharding.ClusterSharding(context.system.toClassic).shardTypeNames.foreach(region => {
    context.log.info(region)
})`

These names can then be supplied to the akka management GET endpoint `/cluster/shards/<shardTypeName>` to get the relevant stats such as `shardId` and `numEntities`. 

This information can be displayed for each member of the cluster visual as a separate UI node element. Further clicking on this shard element can retrieve the entity IDs present in the shard.
